export enum Scheme {
  ArkDark = "arkDark",
  Darker = "darker",
  DeepOcean = "deepOcean",
  Dracula = "dracula",
  Github = "github",
  Lighter = "lighter",
  LightOwl = "lightOwl",
  MonokaiPro = "monokaiPro",
  NightOwl = "nightOwl",
  Oceanic = "oceanic",
  OneDark = "oneDark",
  OneLight = "oneLight",
  Palenight = "palenight",
  SolarizedDark = "solarizedDark",
  SolarizedLight = "solarizedLight",
}
